[default.probe]
protocol = "Swd"

[default.general]
chip = "STM32G070RBTx"    # bluepill
#chip = "STM32F303VCTx"  # discovery-stm32f303

[default.rtt]
enabled = false
# The duration in ms for which the logger should retry to attach to RTT.
timeout = 300

[default.gdb]
enabled = false