[package]
name = "testeLed"
version = "0.1.0"
edition = "2021"


[dependencies]
stm32g0xx-hal = { version = "0.2.0", features = ["rt", "stm32g070"] }
cortex-m-rtic = "1.1.4"
systick-monotonic = "1.0.1"
panic-halt = "0.2.0"





